### ISSUE TITLE
Getting error after successfully logging in

### ISSUE THREAD

**Issue by TonyGregg** [onelogin/onelogin-oidc-java#4] opened 2020-06-29 21:58 UTC
After successfully verifying the user name / password & the control comes back to call back - localhost:8081/login, I see an 401 error from localhost:8081/login

Why? I just followed the code and instructions as given.

**Comment by bvaisakh** [comment] 2022-01-21 07:12
Same issue happens for me as well.

**Comment by dyrczyk** [comment] 2022-01-28 01:54
Duplicate of https://github.com/onelogin/onelogin-oidc-java/issues/14

**Closed as completed** 2022-01-28 02:31 UTC
